### ISSUE TITLE
`TimeBasedAccountCreateRequest` missing "isFlexible" property:

### ISSUE THREAD

**Issue by Tiernan-Stapleton** [logzio/logz-docs#1052]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [x] Issue with the API

**The problematic page**: https://github.com/logzio/logz-docs/blob/master/_source/api/logzio-public-api.yml#L3955

#### Describe the issue

The API spec defined for the TimeBasedAccountCreateRequest refers to an "isFlexible" field in the description for the "reservedDailyGB" field. This "isFlexible" field is not itself in the API spec's properties. 

#### Recommended fix

Add an "isFlexible" field under the `properties` field of TimeBasedAccountCreateRequest.

**Comment by nico-shishkin** [comment]
Solved by https://github.com/logzio/logz-docs/pull/1210
