### ISSUE TITLE
stackdriver.md not clear + link broken

### ISSUE THREAD

**Issue by heygambo** [logzio/logz-docs#1086]
#### Type of issue

- [ ] Typo
- [x] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: https://docs.logz.io/shipping/log-sources/stackdriver.html

#### Describe the issue

It's unclear if this docker container `logzio/logzio-pubsub` has to run forever or if it's a one off task?

In the docs it says:
"You can use Google Cloud Pub/Sub to forward your logs from Stackdriver to Logz.io."

Will Pub/Sub forward to logz.io directly or is the docker container involved in that?

#### Recommended fix

Describe what the docker container is for.

**Comment by YajB** [comment]
@heygambo - Thanks for bringing this issue to our attention. I've asked our Integrations team to look into this matter.

**Comment by nico-shishkin** [comment]
@heygambo , thanks for your feedback, we added some clarification to the document - https://github.com/logzio/logz-docs/pull/2067
