### ISSUE TITLE
Broken link in stackdriver page

### ISSUE THREAD

**Issue by heygambo** [logzio/logz-docs#1087]
Issue resolved in https://github.com/logzio/logz-docs/pull/1215

#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [x] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: https://docs.logz.io/shipping/log-sources/stackdriver.html#build-your-pubsub-input-yaml-file

#### Describe the issue

Link is broken:
https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-google-pubsub.html#filebeat-input-google-pubsub

#### Recommended fix

Link to correct place

**Comment by YajB** [comment]
@heygambo -
Thanks for letting us know. We've fixed the issue you reported with https://github.com/logzio/logz-docs/pull/1215
