### ISSUE TITLE
Extra quote in sample makes the cURL unusable without editing

### ISSUE THREAD

**Issue by AmiStrn** [logzio/logz-docs#1119]
https://github.com/logzio/logz-docs/blob/e6a5b46cd5f8b1db6171b63092936db29e8409ae/_source/api/logzio-public-api.yml#L731

**Comment by YajB** [comment]
@AmiStrn - 
Please confirm that we can close this issue. 
10 x

**Comment by nico-shishkin** [comment]
Solved
