### ISSUE TITLE
Invalid OpenAPI 2.0 specification:

### ISSUE THREAD

**Issue by Tiernan-Stapleton** [logzio/logz-docs#1208]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [x] Issue with the API

**The problematic page**: 
https://github.com/logzio/logz-docs/blob/master/_source/api/logzio-public-api.yml#L364
https://github.com/logzio/logz-docs/blob/master/_source/api/logzio-public-api.yml#L3236
https://github.com/logzio/logz-docs/blob/master/_source/api/logzio-public-api.yml#L448

#### Describe the issue

I am attempting to generate a golang client of your API, using https://github.com/go-swagger/go-swagger v0.27.0.
When running the command
```cli
$ swagger generate client -f ./logzio_api.yml --template=stratoscale
```

I get the following spec validation errors, and am unable to generate a golang client. 
(The 'stratoscale' template style is being used so that the generated client returns errors instead of panicing on errors, and it allows for easier generation of mocks, because of the way that endpoints are encoded.)

```
The swagger spec at "...../logzio_api.yml" is invalid against swagger specification 2.0. see errors :
- "paths./v2/security/rules/search.post.parameters" must validate one and only one schema (oneOf). Found none valid
- paths./v2/security/rules/search.post.parameters.schema.oneOf in body is a forbidden property
- "paths./v1/alerts/triggered-alerts.post.parameters" must validate one and only one schema (oneOf). Found none valid
- paths./v1/alerts/triggered-alerts.post.parameters.in in body should be one of [header]
- paths./v1/alerts/triggered-alerts.post.parameters.in in body should be one of [body]
- "paths./v1/account-management/time-based-accounts/{id}.put.parameters" must validate one and only one schema (oneOf). Found none valid
- paths./v1/account-management/time-based-accounts/{id}.put.parameters.schema.oneOf in body is a forbidden property
- "paths./v1/account-management/time-based-accounts.post.parameters" must validate one and only one schema (oneOf). Found none valid
- paths./v1/account-management/time-based-accounts.post.parameters.schema.oneOf in body is a forbidden property
```

The issue seems to stemming from the usage of the
```yaml
     parameters:
        - in: body
          name: foo
          schema:
            oneOf:
              - $ref: '#/definitions/A'
              - $ref: '#/definitions/B'
```
schema style, where the 'oneOf' is not valid OpenAPI 2.0 spec.

**Comment by YajB** [comment]
@Tiernan-Stapleton,
Thanks for bringing this to our attention. Will have our team look into the issue.

**Comment by YajB** [comment]
Resolved in https://github.com/logzio/logz-docs/pull/1210
