### ISSUE TITLE
Incorrect maven version

### ISSUE THREAD

**Issue by deniskristov** [logzio/logz-docs#1362]
#### Type of issue

- [x] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 
https://docs.logz.io/shipping/log-sources/java.html#logback-config

#### Describe the issue
Incorrect maven version
<version>1.0.25</version>

#### Recommended fix
Correct maven version
<version>v1.0.25</version>
https://mvnrepository.com/artifact/io.logz.logback/logzio-logback-appender/v1.0.25

**Comment by nico-shishkin** [comment]
Hi @deniskristov , thank you very much for the feedback. This has been fixed.
