### ISSUE TITLE
permalink Link with  public short URL does not work

### ISSUE THREAD

**Issue by anirudh16b** [logzio/logz-docs#1382]
We are using your enterprise account. When we share the snapshot as public Long URL it works. However, when we use public Short-URL, the Dashboard permalink generated with "Saved as Snapshot" or "Saved as Object" gives a 02 - Bad Gateway. 
Only For enterprise users for the account, we have SSO login through which the public Short URL works.

**Comment by nico-shishkin** [comment]
Hi @anirudh16b , thank you for bringing this to our attention. We are currently working on this issue and expect it to be resolved soon. For more updates and assistance on this, please contact our support team either via the in-app chat or by emailing help@logz.io. Thank you.
cc @boofinka

**Comment by nico-shishkin** [comment]
Hi @anirudh16b , apologies for the delay in getting back to you. This issue has now been fixed.
