### ISSUE TITLE
JQL search option not unable for Dashboards using Public Link

### ISSUE THREAD

**Issue by anirudh16b** [logzio/logz-docs#1392]
Hello
We are using your enterprise account. While we share the public link on our Logz Dashboards, stakeholders are not able to search data using JQLs with the shared link. Not sure if this is the way its configured. Could you help us on this?

Regards,
Aniruddha

**Comment by YajB** [comment]
Thank you for contacting us, @anirudh16b  - 

I've tagged a couple members of our support team to assist you. 
@ralongit and @boofinka  - would you please look into this issue?

**Comment by ralongit** [comment]
Hi @anirudh16b ,

I'm Raul from the support team. 

JQL isn't supported by Kibana, only lucene & KQL syntaxes are supported.

You can refer to our email address: help@logz.io or to our in-app chat so we will continue the discussion as we don't provide support through Github.

**Comment by YajB** [comment]
Closing the PR - Does not relate to a documentation issue.  
Support was tagged and replied to our user.
