### ISSUE TITLE
the maven dependency can't be found in standard repos.  why isn't it on mvnrepository.com?

### ISSUE THREAD

**Issue by goodale** [logzio/logz-docs#1393]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [x] Missing important information
- [ ] Missing link
- [x] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**:

**Comment by goodale** [comment]
I followed the instructions for log4j2 but get a missing artifact error for io.logz.log4j2.   my pom uses standard repo.  I also can't find the artifact on mvnrepository.com, which is a popular go-to place for such things.  If a private repo is required then the instructions should provide this information so the repo can be added to the pom file (though that will likely be hesitant to use the library too as it may mean the library may also not be open source)

**Comment by nico-shishkin** [comment]
Hi @goodale , thank you for your feedback. The artifact can be found in the Maven central repo at https://search.maven.org/artifact/io.logz.log4j2/logzio-log4j2-appender. I have updated the instructions accordingly. Please let me know if this solves the issue. Thanks.

**Comment by goodale** [comment]
thank you
