### ISSUE TITLE
Confusing text in limitations section

### ISSUE THREAD

**Issue by barakm** [logzio/logz-docs#1539]
#### Type of issue

- [ ] Typo
- [X] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 
https://docs.logz.io/user-guide/archive-and-restore/
#### Describe the issue
Current text:
Each account (or sub-account) should archive to a separate S3 bucket.
If the restore process exceeds the max, the process will fail.
The max data to restore is equivalent to your account’s daily reserved volume, and no more than 100 GB.
Restore processes are capped at 100 GB. This maximum applies to accounts with a daily reserved volume greater than 100 GB.

#### Recommended fix
The text here seems confusing. I am honestly not sure what are the limitations here.

**Comment by YajB** [comment]
@barakm - WDYT? 

> Each account (or sub-account) should archive to a separate S3 bucket.
> 
> The maximum amount of data that can be restored is equal to your account’s daily reserved volume and is capped at 100 GB for all accounts (including accounts with a daily reserved volume greater than 100 GB).
> 
> If the restore process exceeds this maximum, the process fails.
>

**Comment by barakm** [comment]
Much better.

**Comment by YajB** [comment]
@barakm  - but is it good enough?

**Comment by YajB** [comment]
Resolved in https://github.com/logzio/logz-docs/pull/1567
