### ISSUE TITLE
Should this be Microsoft 365 or Office 365? 

### ISSUE THREAD

**Issue by YajB** [logzio/logz-docs#1568]
#### Type of issue
Nomenclature! 
Is the SIEM log data coming from Microsoft 365 or Office 365? There is a difference. 
If the integration is valid for both, the logo text and the topic should clarify this. 

Also, use of the abbreviation "M365" is not Microsoft standard, and may be ambiguous.  Should be corrected throughout the topic. 

- [ ] Typo
- [x] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: [Ship logs from Microsoft Office 365](https://docs.logz.io/shipping/security-sources/office365.html)

**Comment by nico-shishkin** [comment]
Hi @YajB , the integration currently covers the following MS 365 APIs:

Audit.AzureActiveDirectory
Audit.Exchange
Audit.SharePoint
Audit.General (includes all other workloads not included in the previous content types)
DLP.All (DLP events only for all workloads)

So, it's more than just the Office but less than the whole MS suite. 

cc @Doron-Bargo

**Comment by YajB** [comment]
Thanks @nico-shishkin  - 
What do you recommend be changed in the docs to clarify?

**Comment by YajB** [comment]
Closed by @nico-shishkin 's update to the docs
