### ISSUE TITLE
Not enough information for proper running docker container

### ISSUE THREAD

**Issue by dovhanrg** [logzio/logz-docs#1577]
#### Type of issue

- [ ] Typo
- [x] Unclear or confusing
- [x] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 
https://docs.logz.io/shipping/log-sources/docker.html#run-the-docker-image

#### Describe the issue
Not enough information for proper running docker container. Missed required param LOGZIO_URL.
In the docker run script missed LOGZIO_URL variable `... --env LOGZIO_URL="<LISTENER-URL>:5015" ...`, according to [logzio/docker-collector-logs](https://hub.docker.com/r/logzio/docker-collector-logs) page on Docker Hub.

#### Recommended fix

Before fix:
```
docker run --name docker-collector-logs \
--env LOGZIO_TOKEN="<<LOG-SHIPPING-TOKEN>>" \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
-v /var/lib/docker/containers:/var/lib/docker/containers \
logzio/docker-collector-logs
```

Add `--env LOGZIO_URL="<LISTENER-URL>:5015"`
After fix:
```
docker run --name docker-collector-logs \
--env LOGZIO_TOKEN="<ACCOUNT-TOKEN>" \
--env LOGZIO_URL="<LISTENER-URL>:5015" \
-v /var/run/docker.sock:/var/run/docker.sock:ro \
-v /var/lib/docker/containers:/var/lib/docker/containers \
logzio/docker-collector-logs
```

**Comment by YajB** [comment]
@dovhanrg Thank you for raising this issue, Roman!

Our Integrations team will look into improving this topic per your suggestions.

**Comment by yotamloe** [comment]
The listener address has a default value of `listener.logz.io:5015`, you can add the `LOGZIO_REGION` parameter depending on your region to construct a new address as explained in the doc. However, we can add an explanation about `LISTENER-URL` in the parameters table

**Comment by nico-shishkin** [comment]
Hi @dovhanrg , thanks for your suggestion. We have updated the document.
