### ISSUE TITLE
Unclear protocol

### ISSUE THREAD

**Issue by barakm** [logzio/logz-docs#1772]
#### Type of issue

- [ ] Typo
- [X] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 
https://docs.logz.io/user-guide/log-shipping/log-shipping-troubleshooting.html
#### Describe the issue
This protocol: "TLS/SSL over TCP" does not mean anything. Technically speaking, it does nothing to tell you how to send logs here. I have no idea what it means.

**Comment by RefaelMi** [comment]
Thanks for letting us know! 

We're in the middle of creating a dedicated troubleshooting guide for each integration. 

Here is for example a troubleshooting guide for Filebeat: https://docs.logz.io/user-guide/log-troubleshooting/filebeat-troubleshooting.html
