### ISSUE TITLE
give additional information on creating a sub account - email of admin

### ISSUE THREAD

**Issue by imnotashrimp** [logzio/logz-docs#260]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [x] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: docs.logz.io/api

#### Describe the issue

![image](https://user-images.githubusercontent.com/6845404/61201021-df932a80-a6eb-11e9-9ebb-30719490d132.png)

Today, we say "Account administrator's email address" - this is incomplete.

#### Recommended fix

Update to include this information:

- [ ] admin of the account being created (this isn't clear from what's written today)
- [ ] this email needs to be an existing admin on the main account

**Comment by shalper** [comment]
corrected
