### ISSUE TITLE
GuardDuty Lambda

### ISSUE THREAD

**Issue by zdhamilton** [logzio/logz-docs#327]
#### Type of issue

- [ ] Typo
- [x] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 

#### Describe the issue

Docs page: https://docs.logz.io/shipping/log-sources/guardduty.html

In the table with the required environment variables, for "URL" is gives you the list of Logz.io listeners by region from a hyperlink. The formatted string from the the Kinesis Lambda's Python  is: "logzio_url = "{0}/?token={1}".format(os.environ['URL'], os.environ['TOKEN'])". In the case that someone only provides "listener.logz.io" (for example) as it's displayed in the list of listeners by region for the URL environment variable, the endpoint for the Lambda will be missing port 8071. 

Python Lambda: https://github.com/logzio/logzio_aws_serverless/blob/master/python3/kinesis/src/lambda_function.py

#### Recommended fix

Adding something that made it clear that you need the value of the URL variable to be the listener URL and port 8071, such as "find your listener URL from the following hyperlink, and then format it as such: <LISTENER_URL>:8071" would hopefully make the logzio_url variable in the python script not fail.

**Comment by shalper** [comment]
Fixed
