### ISSUE TITLE
Logz.io AWS account ID

### ISSUE THREAD

**Issue by SamCritch** [logzio/logz-docs#331]
#### Type of issue

- [ ] Typo
- [x] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

https://docs.logz.io/user-guide/give-aws-access-with-iam-roles/

#### Describe the issue

This page is unclear. Step 1 "Copy Logz.io details" needs an 'Account ID'. Presumably this is Logz.io's AWS Account ID which I need to paste into the role creation in my own AWS account in step 2 ("Another AWS Account" -> "Account ID"). But where do I get the Logz.io AWS Account ID from? I can't find it anywhere.

#### Recommended fix

Explain where to get the Logz.io AWS Account ID, or, if that's not what is required, which piece of information _is_ required.

**Comment by YajB** [comment]
@nico -may I have your help to improve this page?

**Comment by RefaelMi** [comment]
Hi Sam!

Thanks for letting us know! We released a new version of the docs on how to configure an S3 bucket by using an IAM role - which has much more details and is much clearer to follow up with!

You can check it out here- https://docs.logz.io/user-guide/give-aws-access-with-iam-roles/
