### ISSUE TITLE
Deprecated APIs Removed In Kubernetes v1.16

### ISSUE THREAD

**Issue by cjslack** [logzio/logz-docs#332]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [ x] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: https://docs.logz.io/shipping/log-sources/kubernetes.html

#### Describe the issue

Issue is described best here: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

#### Recommended fix

Ran into this when trying to ship Kubernetes logs on the newest version. I had to make a couple small changes the `logzio-daemonset.yml` file to successfully ship. 

`apiVersion: extensions/v1beta1` to `apiVersion: apps/v1`

and add the following object to `spec`:

```
selector:
  matchLabels:
    k8s-app: fluentd-logzio
    version: v1
```

**Comment by idohalevi** [comment]
@imnotashrimp the fix doesn't require any doc changes

**Comment by imnotashrimp** [comment]
@cjslack sorry for the late response - Our awesome integrations team fixed this in the original repo a while back, so I'll close this issue.

Thanks!
