### ISSUE TITLE
Archive Docs: Missing IAM Role Config

### ISSUE THREAD

**Issue by zdhamilton** [logzio/logz-docs#372]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [x] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 

#### Describe the issue

We're missing the documentation for setting this up with an IAM role configuration.

#### Recommended fix

We should add it since I believe it's the recommended approach now.

**Comment by imnotashrimp** [comment]
Fixed in PR 385. Thanks!
