### ISSUE TITLE
Incorrect cert in "Ship with Logstash over SSL"

### ISSUE THREAD

**Issue by bgeveritt** [logzio/logz-docs#377]
#### Type of issue

- [x] Typo
- [x] Unclear or confusing
- [x] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 

https://docs.logz.io/shipping/shippers/logstash.html

#### Describe the issue

The certificate referenced on this page is incorrect. It should be the certificate found in "Step 3" of the following page: https://app.logz.io/#/dashboard/data-sources/logstash-overssl 

#### Recommended fix

Please update the cert in the documentation to match the cert that is referenced in the "logstash over ssl" section of "Ship Your Data" in Logz.io

**Comment by imnotashrimp** [comment]
Fixed in #381 and #382 . Thanks!
