### ISSUE TITLE
Type field might not be added in Logstash over SSL docs

### ISSUE THREAD

**Issue by zdhamilton** [logzio/logz-docs#401]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [x] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 

#### Describe the issue

Not sure if this is necessary, but along with "add_field { token => ... }" supposed to also include "type => ..."? I don't see type anywhere. Not sure if type is necessary here but not sure how else we would get it. 

#### Recommended fix

Change:
add_field { token => <<SHIPPING_TOKEN>> }

to
add_field { token => <<SHIPPING_TOKEN>>
                   type   => <<LOG_TYPE>> }

**Comment by RefaelMi** [comment]
Hi ! Thanks for letting us know!

We added the Log-type - where it is needed and also the log shipping token, and you can use these docs for an example: 

https://docs.logz.io/shipping/log-sources/curl.html#json-config
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/87263523/181184503-3cbc8fc8-2d5c-4e13-bd52-f69d0cf532f0.png">

 https://docs.logz.io/shipping/log-sources/logstash.html#encrypted
<img width="991" alt="image" src="https://user-images.githubusercontent.com/87263523/181184853-389f83db-96b4-4445-9aeb-801506c1f10a.png">
