### ISSUE TITLE
Hi, I followed the same document however Intergation with Azure AD is not working

### ISSUE THREAD

**Issue by prasunagga** [logzio/logz-docs#410]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**:

**Comment by imnotashrimp** [comment]
Hi @prasunagga, can you paste a link to the page you were using?

**Comment by prasunagga** [comment]
Hi I fixed the same with Logz.io support team. Thanks
