### ISSUE TITLE
Missing role based configuration details

### ISSUE THREAD

**Issue by zdhamilton** [logzio/logz-docs#474]
S3 Archiving page is out of date

#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [x] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 

#### Describe the issue

The above approach shows how to set this up with access key/secret key. Our platform recommends using roles now.

**Comment by imnotashrimp** [comment]
@zdhamilton which page?

**Comment by RefaelMi** [comment]
Hi ! Thanks for letting us know !

Hi Sam! Thanks for letting us know! We released a new version of the docs on how to configure an S3 bucket by using an access key - which has much more details and is much clearer to follow up with!

You can check it out here - https://docs.logz.io/shipping/log-sources/s3-bucket.html#keys
