### ISSUE TITLE
List admin/regular user privileges 

### ISSUE THREAD

**Issue by zdhamilton** [logzio/logz-docs#475]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API
- [x] Suggestion

**The problematic page**: 

#### Describe the issue

Would it make sense to have documentation on the different actions in the account an admin user can do versus a regular user? Apart from tagging features with "admin"

**Comment by YajB** [comment]
Gap in existing documentation will be resolved as we update with information about the Read Only user role & permissions.

**Comment by Simplychee** [comment]
Updated documentation of user role and permissions
