### ISSUE TITLE
Do not set log_raw to true for Vault audit logs

### ISSUE THREAD

**Issue by ngunia** [logzio/logz-docs#524]
#### Type of issue

- [X] Unclear or confusing
- [X] Missing important information

**The problematic page**: https://docs.logz.io/shipping/log-sources/hashicorp-vault.html

#### Describe the issue

In they very first section, you recommend setting "log_raw" to true, so that Filebeat can read the file. This is not advisable, nor true. If you do let log_raw default to false, secret values are replaced by a string containing an hmac-sha256 hash of that secret value. If users do set this to true, they are logging all secret values in plaintext.

Here is an example against a local dev cluster, which you should be able to replicate:

```bash
# you can run the server in another window or just background it
$ vault server -dev -dev-root-token-id=dev &
$ export VAULT_ADDR=http://localhost:8200
$ export VAULT_TOKEN=dev
$ vault audit list
No audit devices are enabled.
$ vault audit enable file file_path=/tmp/logzio.example log_raw=true
Success! Enabled the file audit device at: file/
$ vault write secret/test key="A SECRET VALUE THAT SHOULD NOT BE LOGGED IN RAW"
Success! Data written to: secret/test
$ cat /tmp/logzio.example
{"time":"2020-05-26T18:19:13.991984Z","type":"response","auth":{"client_token":"dev","accessor":"ReoWnERzrXZDShBfghKc2G10","display_name":"token","policies":["root"],"token_policies":["root"],"token_type":"service"},"request":{"id":"546cf1ae-4b9a-b2c2-2675-803f942cf3c1","operation":"update","client_token":"dev","client_token_accessor":"ReoWnERzrXZDShBfghKc2G10","namespace":{"id":"root"},"path":"sys/audit/file","data":{"description":"","local":false,"options":{"file_path":"/tmp/logzio.example","log_raw":"true"},"type":"file"},"remote_address":"127.0.0.1"},"response":{}}
{"time":"2020-05-26T18:19:39.24518Z","type":"request","auth":{"client_token":"dev","accessor":"ReoWnERzrXZDShBfghKc2G10","display_name":"token","policies":["root"],"token_policies":["root"],"token_type":"service"},"request":{"id":"0df16e21-4e22-339b-2db2-a67b1b7345dd","operation":"update","client_token":"dev","client_token_accessor":"ReoWnERzrXZDShBfghKc2G10","namespace":{"id":"root"},"path":"secret/test","data":{"key":"A SECRET VALUE THAT SHOULD NOT BE LOGGED IN RAW"},"remote_address":"127.0.0.1"}}
{"time":"2020-05-26T18:19:39.245431Z","type":"response","auth":{"client_token":"dev","accessor":"ReoWnERzrXZDShBfghKc2G10","display_name":"token","policies":["root"],"token_policies":["root"],"token_type":"service"},"request":{"id":"0df16e21-4e22-339b-2db2-a67b1b7345dd","operation":"update","client_token":"dev","client_token_accessor":"ReoWnERzrXZDShBfghKc2G10","namespace":{"id":"root"},"path":"secret/test","data":{"key":"A SECRET VALUE THAT SHOULD NOT BE LOGGED IN RAW"},"remote_address":"127.0.0.1"},"response":{}}
```

Notice that the secret I wrote, "A SECRET VALUE THAT SHOULD NOT BE LOGGED IN RAW" is logged directly to the log file. Similarly, my dev root token, "dev" is logged in plain in the "auth.client_token" field.

#### Recommended fix

I believe this is just a misunderstanding of how the audit backend works in Vault, so I would remove setting log_raw to true by default in the documentation. Your example will still be valid/functional, and your users will not be logging sensitive data directly to a file nor transmitting it to your servers. For more context, in order to gain use from your audit log in Vault, you should use [/sys/audit-hash](https://www.vaultproject.io/api-docs/system/audit-hash) to generate the hash for a plaintext value, and search your audit log for that hash.

At the very least, you should add a disclaimer that it is possible sensitive data will be transmitted in plaintext if you set log_raw to true, but this is a less secure default.

**Comment by FatnLazy** [comment]
Hi ngunia,

thank you for your post, we are fully aware of everything you noted here.
the reason why we asked to put the log_raw to true is because at this time the Vault only support so little fields that can be decrypted by their decryption command we do have an open request for them that will allow us to decrypt only the fields that we need, when this request will be in their productions( as far as i know they started working on it) we will change the docs so that the log_raw value will stay false.

as far as the audit-hash i will look into it and if it is something we can work with we will update the docs accordingly.

**Comment by ngunia** [comment]
The feature you describe was recently released: https://www.vaultproject.io/docs/commands/secrets/tune#audit-non-hmac-request-keys 

I still think you should at the very least add a disclaimer. Users could be unwittingly sending you API keys, database passwords, etc. and you're storing them in plaintext.

**Comment by shalper** [comment]
Hi @ngunia, 
The issue you raised still persists unfortunately. A note was added to make it clearer that the data  is sent in unencrypted. 
See https://docs.logz.io/shipping/log-sources/hashicorp-vault.html.

Thank you for your feedback,
The Logz.io Team
