### ISSUE TITLE
Account region page has missing text

### ISSUE THREAD

**Issue by barakm** [logzio/logz-docs#575]
#### Type of issue

- [X] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: https://docs.logz.io/user-guide/accounts/account-region.html

#### Describe the issue

Text currently reads:
"To find your region, sign in to Logz.io and look at the URL in the address bar. If you see app.logz.io, then your account is in the . All other regions have a hypen and then a two-letter region code. For example, if you see app-eu.logz.io, then your account is in the ."

#### Recommended fix
Looks like something broke in some css somewhere - the region names are missing

**Comment by shalper** [comment]
@barakm Thanks for reporting this! It's fixed.

**Comment by barakm** [comment]
@shalper since we are on this page anyway, the text currently reads that: "You can find your account’s region by selecting  > Settings > General from the top menu."

From my account, the General Settings page does not include any indication of the region.
