### ISSUE TITLE
Region not available in Settings page

### ISSUE THREAD

**Issue by barakm** [logzio/logz-docs#588]
#### Type of issue

- [ ] Typo
- [X] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**:  https://docs.logz.io/user-guide/accounts/account-region.html

#### Describe the issue

Current text says: "You can find your account’s region by selecting  > Settings > General from the top menu."
But no such information is available.

![image](https://user-images.githubusercontent.com/294080/87521071-865a3000-c68c-11ea-9e2a-d7cf464d4b0c.png)

**Comment by shalper** [comment]
You're right. It only appears if you're an account admin. Fixed. Thanks for reporting this ;)

**Comment by barakm** [comment]
Is this intentional?
Even as a non-admin, I would definitely want to know the region.
As the person implementing the integration, I would DEFINITELY need to know
the region.
