### ISSUE TITLE
Sentence appears twice

### ISSUE THREAD

**Issue by barakm** [logzio/logz-docs#709]
#### Type of issue

- [ X] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 
https://docs.logz.io/user-guide/integrations/custom-endpoints.html

#### Describe the issue
The sentence "The Logz.io IP range is used by all customers and should be treated with caution." appears twice.
![image](https://user-images.githubusercontent.com/294080/97102762-e3fd1000-16b0-11eb-9109-34a9452b3f31.png)

#### Recommended fix
Fixed in PR711: - https://deploy-preview-711--logz-docs.netlify.app/user-guide/integrations/custom-endpoints.html

**Comment by YajB** [comment]
Fixed in #711. - https://deploy-preview-711--logz-docs.netlify.app/user-guide/integrations/custom-endpoints.html
