### ISSUE TITLE
Missing source IP address for notifications

### ISSUE THREAD

**Issue by barakm** [logzio/logz-docs#710]
Resolved in PR https://github.com/logzio/logz-docs/pull/1220

#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [X ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 
https://docs.logz.io/user-guide/integrations/custom-endpoints.html
#### Describe the issue
Custom notifications are sent from logz.io servers, with the actual request originating from one of our IP addresses. A secure integration must open their firewalls to allow traffic from these IPs. The list of IPs should be available (or linked) from this page.

#### Recommended fix
Add the list of source IP addresses, or link to where they can be found.

**Comment by schwin007** [comment]
We need to document that we only allow outgoign traffic to 80 and 443, non standard ports are not supported.

**Comment by boofinka** [comment]
> We need to document that we only allow outgoign traffic to 80 and 443, non standard ports are not supported.

We specify it on the [notification endpoint doc](https://docs.logz.io/user-guide/integrations/endpoints.html#to-manage-notification-endpoints). Is it relevant to anything else?

**Comment by barakm** [comment]
The information about port 80 and 4433 is also available in the custom integration doc. These are the only relevant places.
The source IP address is required in the custom integration page.

**Comment by YajB** [comment]
**_Where is this list of source IP addresses, so I know where to link to?_** 
> 
> #### Recommended fix
> Add the list of source IP addresses, or link to where they can be found.

**Comment by barakm** [comment]
Ofer and/or Roi have this information

**Comment by YajB** [comment]
@barakm & @boofinka  - I believe this issue is resolved. 
Please confirm that I can close it.

**Comment by barakm** [comment]
It is incomplete - the table lists five regions. We have seven. The five listed IPs look like the AWS ones. Azure regions are not listed.
Also, why is it called 'Region slug'?

**Comment by YajB** [comment]
@barakm 

1. Please provide the missing region information or point me to someone who can. Which Azure regions are missing?
2.  What should the column header be instead of **Region slug**?

**Comment by barakm** [comment]
1. @ofer-velich is probably the right person.
2. 'Region Name' seems good to me. We may need to add another column for 'Cloud' (possible values: AWS, Azure)

**Comment by barakm** [comment]
1. @ofer-velich will know
2. 'Region Name' sounds good to me.
3. We should probably have a 'Cloud Name' field, with possible values of: AWS, Azure

The full list of regions (including currently inactive ones):
![image](https://user-images.githubusercontent.com/294080/126268592-c6bfab5f-e2e2-43e7-985e-8ed279f34a37.png)

**Comment by ofer-velich** [comment]
we are missing NAT gateway on these regions
we will resolve it in couple of weeks 
fyi - https://logzio.atlassian.net/browse/OPS-30

**Comment by barakm** [comment]
@ofer-velich I don't understand. How are notifications currently sent from azure regions?

**Comment by YajB** [comment]
Resolved in PR https://github.com/logzio/logz-docs/pull/1220
