### ISSUE TITLE
Wrong 'How to get you region code' pic

### ISSUE THREAD

**Issue by yyyogev** [logzio/logz-docs#836]
#### Type of issue

- [ ] Typo
- [x] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [ ] Bug in the docs code or a template
- [ ] Issue with the API

**The problematic page**: 

#### Describe the issue

This image of how to find your region code [here](https://docs.logz.io/user-guide/accounts/account-region.html#available-regions) is wrong.
Image link: https://dytvr9ot2sszz.cloudfront.net/logz-docs/distributed-tracing/general-settings1.png
#### Recommended fix

The region code should be taken from here:
https://docs.logz.io/user-guide/accounts/account-region.html#available-regions

**Comment by YajB** [comment]
Hi Yogev - 

Do you mean that [this image](https://dytvr9ot2sszz.cloudfront.net/logz-docs/distributed-tracing/general-settings1.png) on the  [getting started page for tracing](https://docs.logz.io/user-guide/distributed-tracing/getting-started-tracing/) is incorrect?  

The image displayed is identical to what a user sees when they click the link [in this section of the Regions page](https://docs.logz.io/user-guide/accounts/account-region.html#available-regions)

**Comment by YajB** [comment]
This issue resolved in https://github.com/logzio/logz-docs/pull/835

Changed image to guide users to take 2-letter code at start of region designation: 

- https://docs.logz.io/user-guide/distributed-tracing/getting-started-tracing/%20%20%20#look-up-your-distributed-tracing-token-and-region-information-in-logzio
- added same guidance to accounts > regions topic: https://docs.logz.io/user-guide/accounts/account-region.html#how-to-look-up-your-account-region
