### ISSUE TITLE
Slack button is useless!

### ISSUE THREAD

**Issue by hadilq** [logzio/logz-docs#854]
#### Type of issue

- [ ] Typo
- [ ] Unclear or confusing
- [ ] Missing important information
- [ ] Missing link
- [X] Bug in the docs code or a template
- [ ] Issue with the API

The Slack button is on most of the pages.

#### Describe the issue
Whenever I try to use the Slack button I have to fill out the "I am not robot!" where is appearing in a small box that I cannot fill it correctly. It's like:
<img width="517" alt="Screenshot 2021-01-08 at 10 06 08" src="https://user-images.githubusercontent.com/5190539/103997240-235cd800-519b-11eb-8abb-12cd2280e771.png">

My browser is Firefox 80.0.1.

**Comment by shalper** [comment]
@hadilq Thank you for pointing out this issue! We apologize for the delay in our response. We're looking into it and hope to have it resolved asap.

**Comment by RefaelMi** [comment]
Hi! Thanks for letting us know!

We removed the slack button from all the integrations.
